apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nxze
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-nxze@sha256:e242b325c5bc62a98493d9b1219c53035d0d892c25673c9c85cce7ea3c2269dc
        name: my-nodejs
        resources: {}
status: {}
